name: telnyx_common_example
description: A basic example demonstrating the use of the telnyx_common module.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  telnyx_common:
    path: ../
  firebase_messaging: ^16.0.0
  firebase_core: ^4.0.0
  permission_handler: ^11.3.1

dependency_overrides:
  flutter_webrtc: ^0.14.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true