name: telnyx_common
description: A high-level, state-agnostic, drop-in module for the Telnyx Flutter SDK that simplifies WebRTC integration.
version: 0.0.1-beta
homepage: https://telnyx.com/
repository: https://github.com/team-telnyx/flutter-voice-commons
issue_tracker: https://github.com/team-telnyx/flutter-voice-commons/issues


environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  telnyx_webrtc: ^2.0.1
  flutter_callkit_incoming: ^2.5.8
  uuid: ^4.0.0
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^19.3.0
  shared_preferences: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.0
  build_runner: ^2.4.0

flutter: